Repository WFCD/warframe-items, pull requests merged in 2019-10, with the labels that each got.

#112 chore: auditing fixes
  package-lock.json
  package.json
Labels: Scope: CI, Severity4: Inconvenient, Type: Maintenance

#111 fix: Augments
  build/parser.js
Labels: Scope: Data, Type: Enhancement

#114 fix: overrides not applying properly
  build/parser.js
Labels: Scope: Data, Severity2: Major, Type: Bug

#115 fix: readme version updating on builds
  build/build.js
Labels: Scope: Documentation, Type: Maintenance

#116 sorting without data json committed
  build/parser.js
Labels: Scope: Data, Severity4: Inconvenient, Type: Enhancement
